import Mathlib.NumberTheory.LSeries.PrimesInAP
import PrimeNumberTheoremAnd.Chebotarev.Cyclotomic.PrimeSeries

/-!
## Prime-filtered coefficients: rewriting `LSeries` as a sum over `Nat.Primes`

Later analytic arguments (Euler products / logarithms) are most naturally phrased as sums over primes.
This file provides a small algebraic bridge: the `LSeries` of the prime-filtered coefficient
function `primeCoeff` can be written as a `tsum` indexed by `Nat.Primes`.

No analytic estimates are used here.
-/

namespace PrimeNumberTheoremAnd

namespace Chebotarev
namespace Cyclotomic

open scoped Classical BigOperators

open LSeries

section

variable {n : ℕ}

/-- The `LSeries` of `primeCoeff χ` is supported on prime powers (in fact, only primes). -/
lemma support_term_primeCoeff_subset_isPrimePow (χ : DirichletCharacter ℂ n) (s : ℂ) :
    Function.support (LSeries.term (primeCoeff (n := n) χ) s) ⊆ {m : ℕ | IsPrimePow m} := by
  intro m hm
  have hm0 : m ≠ 0 := by
    intro h
    subst h
    simp [LSeries.term] at hm
  have hprime : m.Prime := by
    by_contra hprime
    have : primeCoeff (n := n) χ m = 0 := by simp [primeCoeff, hprime]
    have : LSeries.term (primeCoeff (n := n) χ) s m = 0 := by simp [LSeries.term, hm0, this]
    exact hm (by simpa [Function.mem_support] using this)
  -- primes are prime powers
  exact hprime.isPrimePow

open Nat.Primes in
/--
If the `LSeries` of `primeCoeff χ` is summable at `s`, then it equals the sum over primes of its
terms. (This uses the `tsum` decomposition over prime powers from `Mathlib`.)
-/
theorem LSeries_primeCoeff_eq_tsum_primes {n : ℕ} (χ : DirichletCharacter ℂ n) (s : ℂ)
    (hs : LSeriesSummable (primeCoeff (n := n) χ) s) :
    LSeries (primeCoeff (n := n) χ) s = ∑' p : Nat.Primes, LSeries.term (primeCoeff (n := n) χ) s p := by
  -- start from the `tsum` decomposition into primes and higher prime powers
  have hsupport := support_term_primeCoeff_subset_isPrimePow (n := n) χ s
  have hsum : Summable (LSeries.term (primeCoeff (n := n) χ) s) := hs
  -- Use the additive lemma generated by `to_additive` in `PrimesInAP`.
  have hdecomp :=
    (tsum_eq_tsum_primes_add_tsum_primes_of_support_subset_prime_powers
      (f := LSeries.term (primeCoeff (n := n) χ) s) hsum hsupport)
  -- The contribution from prime powers `p^(k+2)` vanishes, since `primeCoeff` is zero there.
  have hpow_zero :
      (∑' (p : Nat.Primes) (k : ℕ), LSeries.term (primeCoeff (n := n) χ) s (p ^ (k + 2))) = 0 := by
    have h0 : ∀ (p : Nat.Primes) (k : ℕ),
        LSeries.term (primeCoeff (n := n) χ) s (p ^ (k + 2)) = 0 := by
      intro p k
      have hnp : ¬ (p.1 ^ (k + 2)).Prime := by
        have : (2 : ℕ) ≤ k + 2 :=
          Nat.succ_le_succ (Nat.succ_le_succ (Nat.zero_le k))
        exact Nat.Prime.not_prime_pow (x := p.1) (n := k + 2) this
      simp [LSeries.term, primeCoeff, hnp]
    simp [h0]
  -- finish
  simpa [LSeries, hpow_zero, add_zero] using hdecomp

end

end Cyclotomic
end Chebotarev

end PrimeNumberTheoremAnd
