import Mathlib.FieldTheory.Galois.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
## Chebotarev reduction: fixed field of a cyclic subgroup

Sharifi’s reduction step (Thm 7.2.2, Step 1) passes from a conjugacy class `C ⊆ Gal(L/K)` to the
intermediate field `E = L^{⟨σ⟩}` fixed by the cyclic subgroup generated by `σ ∈ C`.  The extension
`L/E` then has cyclic Galois group.

This file expresses the corresponding **purely algebraic** facts using mathlib’s Galois
correspondence (`IntermediateField.fixedField` / `IntermediateField.subgroupEquivAlgEquiv`).

No analytic input appears here.
-/

namespace PrimeNumberTheoremAnd

namespace Chebotarev

open scoped Classical

section

variable (K L : Type*) [Field K] [Field L] [Algebra K L]

variable (σ : Gal(L/K))

/-- The intermediate field fixed by the cyclic subgroup generated by `σ`. -/
def fixedFieldZpowers : IntermediateField K L :=
  IntermediateField.fixedField (Subgroup.zpowers σ)

@[simp]
lemma fixedFieldZpowers_def :
    fixedFieldZpowers (K := K) (L := L) σ = IntermediateField.fixedField (Subgroup.zpowers σ) := rfl

variable [FiniteDimensional K L]

/-- Galois correspondence: the fixing subgroup of `L^{⟨σ⟩}` is exactly `⟨σ⟩`. -/
@[simp]
lemma fixingSubgroup_fixedFieldZpowers :
    (fixedFieldZpowers (K := K) (L := L) σ).fixingSubgroup = Subgroup.zpowers σ := by
  simpa [fixedFieldZpowers] using
    (IntermediateField.fixingSubgroup_fixedField (F := K) (E := L) (H := Subgroup.zpowers σ))

/--
The Galois group of `L` over the fixed field of `⟨σ⟩` is cyclic.

This is immediate from the canonical isomorphism
`Subgroup.zpowers σ ≃* Gal(L / fixedField (Subgroup.zpowers σ))`.
-/
theorem isCyclic_gal_fixedFieldZpowers :
    IsCyclic (Gal(L/fixedFieldZpowers (K := K) (L := L) σ)) := by
  let e :  (Subgroup.zpowers σ) ≃*
        Gal(L / IntermediateField.fixedField (Subgroup.zpowers σ)) :=
    IntermediateField.subgroupEquivAlgEquiv (F := K) (E := L) (H := Subgroup.zpowers σ)
  have hcyc : IsCyclic (Subgroup.zpowers σ) := by infer_instance
  simpa [fixedFieldZpowers, e] using (MulEquiv.isCyclic e).1 hcyc

/-!
As a convenient corollary: `Gal(L/L^{⟨σ⟩})` is commutative.

We keep this as a lemma (not a global instance) to avoid unexpected instance search effects.
-/
theorem mul_comm_gal_fixedFieldZpowers (a b : Gal(L/fixedFieldZpowers (K := K) (L := L) σ)) :
    a * b = b * a := by
  classical
  haveI : IsCyclic (Gal(L/fixedFieldZpowers (K := K) (L := L) σ)) :=
    isCyclic_gal_fixedFieldZpowers (K := K) (L := L) σ
  exact mul_comm' a b

/--
Sharifi Step 2: the cyclic subextension `L / L^{⟨σ⟩}` has degree `|⟨σ⟩|`.
-/
theorem finrank_fixedFieldZpowers_eq_natCard_zpowers :
    Module.finrank (fixedFieldZpowers (K := K) (L := L) σ) L =
      Nat.card (Subgroup.zpowers σ) := by
  simpa [fixedFieldZpowers] using
    (IntermediateField.finrank_fixedField_eq_card (F := K) (E := L)
      (H := Subgroup.zpowers σ))

omit [FiniteDimensional K L] in
/--
Sharifi Step 2: the cyclic subextension `L / L^{⟨σ⟩}` is Galois whenever `L/K` is Galois.
-/
theorem isGalois_fixedFieldZpowers_L [IsGalois K L] :
    IsGalois (↥(fixedFieldZpowers (K := K) (L := L) σ)) L :=
  IsGalois.tower_top_intermediateField (fixedFieldZpowers (K := K) (L := L) σ)

omit [FiniteDimensional K L] in
/--
When `⟨σ⟩` is normal in `Gal(L/K)`, the fixed field `L^{⟨σ⟩}` is Galois over `K`.
-/
theorem isGalois_fixedFieldZpowers_K [IsGalois K L] [Subgroup.Normal (Subgroup.zpowers σ)] :
    IsGalois K (fixedFieldZpowers (K := K) (L := L) σ) := by
  simpa [fixedFieldZpowers] using
    (inferInstanceAs (IsGalois K (IntermediateField.fixedField (Subgroup.zpowers σ))))

end

end Chebotarev

end PrimeNumberTheoremAnd
